spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
  spring:
    jackson:
      deserialization:
        FAIL_ON_UNKNOWN_PROPERTIES: false

elasticsearch:
  url: localhost:9200
